use std::collections::BTreeMap;

use serde::{Deserialize, Deserializer, Serialize, Serializer};
use serde_json::Value;

/// Unknown JSON object keys captured during deserialization.
///
/// These fields are reserved for forward-compatible contract data. Do not add
/// keys here that duplicate declared struct fields; write the typed field
/// instead so serialized JSON stays unambiguous.
pub type ExtraFields = BTreeMap<String, Value>;
pub type JsonObject = serde_json::Map<String, Value>;
/// JSON number token preserved exactly for fixture parity.
///
/// Using `serde_json::Number` keeps integer JSON values as integers on
/// round-trip, but it means owning structs derive `PartialEq` rather than `Eq`.
pub type ContractNumber = serde_json::Number;

#[derive(Debug, Clone, Default, PartialEq)]
pub enum MaybePresent<T> {
    #[default]
    Missing,
    Present(Option<T>),
}

impl<T> MaybePresent<T> {
    pub const fn is_missing(&self) -> bool {
        matches!(self, Self::Missing)
    }
}

impl<T> Serialize for MaybePresent<T>
where
    T: Serialize,
{
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        match self {
            Self::Missing => serializer.serialize_none(),
            Self::Present(value) => value.serialize(serializer),
        }
    }
}

impl<'de, T> Deserialize<'de> for MaybePresent<T>
where
    T: Deserialize<'de>,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Option::<T>::deserialize(deserializer).map(Self::Present)
    }
}

/// Seal for [`StringEnum`]: only the `string_enum!` macro (which lives in this
/// crate) can name `Sealed`, so the marker can't be implemented elsewhere. It is
/// `pub(crate)` rather than `pub`, so downstream crates can't reach it either.
pub(crate) mod string_enum_sealed {
    pub trait Sealed {}
}

/// Marker for the forward-compatible enums generated by [`string_enum!`]. Every
/// implementor deserializes *infallibly*: an unrecognized string maps to the
/// enum's `Unknown(String)` variant rather than erroring. `parse_string_enum`
/// bounds on this trait so it can never be instantiated with a stricter enum
/// whose `Deserialize` could fail and turn one bad DB row into a panic
/// (sc-4269 / F-CORE-9).
pub(crate) trait StringEnum:
    string_enum_sealed::Sealed + serde::de::DeserializeOwned
{
}

macro_rules! string_enum {
    (
        $(#[$meta:meta])*
        pub enum $name:ident {
            $($variant:ident => $value:literal),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[non_exhaustive]
        #[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
        pub enum $name {
            $($variant,)+
            Unknown(String),
        }

        impl $crate::contracts::string_enum_sealed::Sealed for $name {}
        impl $crate::contracts::StringEnum for $name {}

        impl $name {
            pub fn as_str(&self) -> &str {
                match self {
                    $(Self::$variant => $value,)+
                    Self::Unknown(value) => value.as_str(),
                }
            }
        }

        impl Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: Serializer,
            {
                serializer.serialize_str(self.as_str())
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: Deserializer<'de>,
            {
                let value = String::deserialize(deserializer)?;
                Ok(match value.as_str() {
                    $($value => Self::$variant,)+
                    _ => Self::Unknown(value),
                })
            }
        }
    };
}

// Re-exported within the crate so sibling contract modules (for example
// `training`) can declare their own forward-compatible string enums with the
// same `Unknown(String)` fallback semantics.
pub(crate) use string_enum;

string_enum! {
    pub enum ContractMode {
        TextToImage => "text_to_image",
        EditImage => "edit_image",
        CharacterImage => "character_image",
        StyleVariations => "style_variations",
        ImageToVideo => "image_to_video",
        TextToVideo => "text_to_video",
        FirstLastFrame => "first_last_frame",
        ExtendClip => "extend_clip",
        VideoBridge => "video_bridge",
        ReplacePerson => "replace_person",
        PersonDetect => "person_detect",
        PersonTrack => "person_track",
        FrameExtract => "frame_extract",
        TimelineExport => "timeline_export",
        ModelDownload => "model_download",
        ModelImport => "model_import",
        LoraImport => "lora_import",
    }
}

string_enum! {
    pub enum RecipeAdapter {
        ProceduralPreview => "procedural_preview",
        ZImageDiffusers => "z_image_diffusers",
        QwenImage => "qwen_image",
        LensTurbo => "lens_turbo",
        SenseNovaU1 => "sensenova_u1",
        FluxDiffusers => "flux_diffusers",
        ChromaDiffusers => "chroma_diffusers",
        KolorsDiffusers => "kolors_diffusers",
        SdxlDiffusers => "sdxl_diffusers",
        ProceduralVideo => "procedural_video",
        ProceduralPersonTracking => "procedural_person_tracking",
        FfmpegFrameExtract => "ffmpeg-frame-extract",
        TimelineExporter => "timeline-exporter",
    }
}

string_enum! {
    pub enum PersonTrackMaskState {
        // "deferred" is the legacy procedural-preview state. Real tracks report
        // segmentation mask states: active (masks for all detected frames),
        // generated (partial), degraded (box fallback / no segmenter), or missing.
        Deferred => "deferred",
        Active => "active",
        Generated => "generated",
        Degraded => "degraded",
        Missing => "missing",
    }
}

string_enum! {
    pub enum PersonTrackCorrectionState {
        // A freshly tracked sidecar advertises that it accepts box corrections.
        ReadyForBoxCorrections => "ready_for_box_corrections",
        // Set once the correction UI has persisted at least one box adjustment or
        // frame rejection into the sidecar's `corrections` array (sc-1485).
        BoxCorrectionsApplied => "box_corrections_applied",
    }
}

string_enum! {
    pub enum CharacterReferenceRole {
        Reference => "reference",
        Hero => "hero",
        TestOutput => "test-output",
    }
}

string_enum! {
    pub enum CharacterLoraCategory {
        Character => "character",
    }
}

string_enum! {
    pub enum JobType {
        Placeholder => "placeholder",
        ImageGenerate => "image_generate",
        ImageEdit => "image_edit",
        ImageVqa => "image_vqa",
        ImageInterleave => "image_interleave",
        VideoGenerate => "video_generate",
        VideoExtend => "video_extend",
        VideoBridge => "video_bridge",
        PersonDetect => "person_detect",
        PersonTrack => "person_track",
        PersonReplace => "person_replace",
        // Whole-body DWPose keypoint detection (photo -> body/hands/face) for the
        // Pose Library (epic 2282). onnxruntime-backed like person_detect; advertised
        // by the Python worker, routed via requested_gpu (not in NON_GPU_JOB_TYPES).
        PoseDetect => "pose_detect",
        // SCRFD 5-point face-landmark extraction from one image (Key Point Library,
        // epic 4422 / sc-4433): photo -> normalized [left_eye, right_eye, nose,
        // mouth_left, mouth_right] in square-canvas [0,1], consumable as an InstantID
        // angle/framing preset (pass-in kps via generate_with_kps). Native-MLX SCRFD on
        // the Rust worker (zero-Python, epic 3482); InsightFace on the Python worker.
        // GPU-routed like pose_detect (not in NON_GPU_JOB_TYPES).
        KpsExtract => "kps_extract",
        // Standalone upscale of an existing image asset (Image Editor, epic 2427).
        // Torch-backed (Real-ESRGAN / AuraSR), GPU-required like generation; reuses
        // the upscale engines that previously only ran as a generation post-step.
        ImageUpscale => "image_upscale",
        // Standalone tile-ControlNet detail refine of an existing image asset (Image
        // Editor, epic 2427; spike sc-2437). Torch-backed SDXL/RealVisXL img2img + a
        // tile ControlNet run over feathered tiles to add micro-texture; GPU-required
        // like generation. Composes after image_upscale (creative upscale).
        ImageDetail => "image_detail",
        FrameExtract => "frame_extract",
        TimelineExport => "timeline_export",
        ModelDownload => "model_download",
        ModelImport => "model_import",
        ModelConvert => "model_convert",
        LoraImport => "lora_import",
        LoraTrain => "lora_train",
        TrainingCaption => "training_caption",
        PromptRefine => "prompt_refine",
    }
}

string_enum! {
    pub enum JobStatus {
        Queued => "queued",
        Preparing => "preparing",
        Downloading => "downloading",
        LoadingModel => "loading_model",
        Running => "running",
        Saving => "saving",
        Completed => "completed",
        Failed => "failed",
        Canceled => "canceled",
        Interrupted => "interrupted",
    }
}

string_enum! {
    pub enum ProgressStage {
        Queued => "queued",
        Preparing => "preparing",
        Downloading => "downloading",
        Importing => "importing",
        LoadingModel => "loading_model",
        Estimating => "estimating",
        Generating => "generating",
        Running => "running",
        // LoRA training stages (status stays `running`); see
        // apps/worker/scene_worker/training_adapters.py.
        CachingLatents => "caching_latents",
        Training => "training",
        Checkpointing => "checkpointing",
        Rendering => "rendering",
        Extracting => "extracting",
        Tracking => "tracking",
        Muxing => "muxing",
        Saving => "saving",
        Completed => "completed",
        Failed => "failed",
        Canceled => "canceled",
        Interrupted => "interrupted",
    }
}

string_enum! {
    pub enum WorkerStatus {
        Idle => "idle",
        Busy => "busy",
        Offline => "offline",
    }
}

string_enum! {
    pub enum WorkerCapability {
        Cpu => "cpu",
        Gpu => "gpu",
        Placeholder => "placeholder",
        ImageGenerate => "image_generate",
        ImageEdit => "image_edit",
        ImageVqa => "image_vqa",
        ImageInterleave => "image_interleave",
        VideoGenerate => "video_generate",
        VideoExtend => "video_extend",
        VideoBridge => "video_bridge",
        PersonDetect => "person_detect",
        PersonTrack => "person_track",
        PersonReplace => "person_replace",
        // Whole-body DWPose keypoint detection (Pose Library, epic 2282). Advertised
        // only by the Python worker when the onnxruntime/rtmlib backend is installed
        // (runtime.py, gated on pose_detector_backend_available); the Rust utility
        // worker never emits it. See jobs_store::worker_supports_job.
        PoseDetect => "pose_detect",
        // SCRFD 5-point face-landmark extraction (Key Point Library, epic 4422 /
        // sc-4433). Advertised by the macOS Rust/MLX worker (native SCRFD, zero-Python)
        // and by the Python worker when the InsightFace backend is installed
        // (runtime.py, gated on kps_extractor_backend_available). See
        // jobs_store::worker_supports_job.
        KpsExtract => "kps_extract",
        // Procedural detection/tracking previews served by the Rust utility worker.
        // Real, model-backed PersonDetect/PersonTrack jobs are served by the Python
        // GPU worker (YOLO/ByteTrack/SAM2); these preview capabilities keep the CPU
        // procedural path claimable only for explicit `preview: true` jobs, so a
        // real job never routes to the placeholder. Segment availability is its own
        // capability for replacement readiness. See jobs_store::worker_supports_job
        // and apps/worker/scene_worker/runtime.py.
        PersonDetectPreview => "person_detect_preview",
        PersonTrackPreview => "person_track_preview",
        // Real person segmentation (SAM2), advertised only by the Python GPU worker
        // (runtime.py, gated on segmenter_backend_available) and consumed by
        // replace-person readiness; the Rust worker never emits it. Not dead — see
        // the API "segment" capability mapping.
        PersonSegment => "person_segment",
        // Standalone image upscale (Image Editor, epic 2427). Advertised by the
        // Python worker when the torch inference backend is available (runtime.py);
        // the Rust utility worker never emits it. See jobs_store::job_requires_gpu.
        ImageUpscale => "image_upscale",
        // Standalone tile-ControlNet detail refine (Image Editor, epic 2427; spike
        // sc-2437). Advertised by the Python worker only when the torch inference
        // backend is available (runtime.py); the Rust utility worker never emits it.
        // See jobs_store::job_requires_gpu.
        ImageDetail => "image_detail",
        FrameExtract => "frame_extract",
        TimelineExport => "timeline_export",
        ModelDownload => "model_download",
        ModelImport => "model_import",
        ModelConvert => "model_convert",
        LoraImport => "lora_import",
        LoraTrain => "lora_train",
        TrainingCaption => "training_caption",
        // Real (non-dry-run) LoRA training execution. Advertised separately from
        // `LoraTrain` (dry-run plan validation, which needs no inference backend)
        // so a real run only routes to a worker that can actually train. See
        // jobs_store::worker_supports_job and apps/worker/scene_worker/runtime.py.
        LoraTrainExecute => "lora_train_execute",
        // Prompt refinement (LLM rewrite of a user prompt). A lightweight, non-GPU
        // job advertised by the Python worker (it only needs an OpenAI-compatible
        // endpoint, not an inference backend); the Rust utility worker never emits
        // it. See jobs_store::NON_GPU_JOB_TYPES and apps/worker/scene_worker/runtime.py.
        PromptRefine => "prompt_refine",
    }
}

string_enum! {
    pub enum SseEvent {
        Ready => "ready",
        Heartbeat => "heartbeat",
        JobUpdated => "job.updated",
        QueueUpdated => "queue.updated",
        WorkerUpdated => "worker.updated",
    }
}

string_enum! {
    /// Asset resource types allowed by the JSON schema.
    ///
    /// Current writers emit `image`, `video`, and frame extraction sidecars;
    /// `upload` and `render` are reserved by the schema and project folders.
    pub enum AssetType {
        Image => "image",
        Video => "video",
        Upload => "upload",
        Frame => "frame",
        Render => "render",
        // An interleaved text-image document (SenseNova-U1). The asset's `file`
        // points to an InterleavedDocument JSON in assets/documents/; the images it
        // references are ordinary `image` assets. See sc-1576.
        Document => "document",
        // A whole-body DWPose skeleton (Pose Library, epic 2282). The asset's `file`
        // points to the rendered skeleton preview; keypoints/hands/face + category live
        // in the sidecar's `pose` field. Stored under a reserved global poses project.
        Pose => "pose",
    }
}

string_enum! {
    pub enum DocumentSegmentKind {
        Text => "text",
        Image => "image",
    }
}

string_enum! {
    pub enum CharacterType {
        Person => "person",
        Creature => "creature",
        Object => "object",
    }
}

string_enum! {
    pub enum TimelineAspectRatio {
        Landscape => "16:9",
        Portrait => "9:16",
        Square => "1:1",
    }
}

string_enum! {
    pub enum TimelineTrackKind {
        Video => "video",
        Overlay => "overlay",
        Audio => "audio",
    }
}

string_enum! {
    pub enum TimelineItemType {
        Video => "video",
        Image => "image",
        Audio => "audio",
    }
}

string_enum! {
    pub enum TimelineFitMode {
        Fit => "fit",
        Fill => "fill",
        Stretch => "stretch",
    }
}

string_enum! {
    pub enum TimelineVersionSource {
        Original => "original",
        Replacement => "replacement",
        Extension => "extension",
        Bridge => "bridge",
        Restore => "restore",
        Manual => "manual",
    }
}

string_enum! {
    pub enum TimelineTransitionType {
        Cut => "cut",
        Crossfade => "crossfade",
        FadeFromBlack => "fade_from_black",
        FadeToBlack => "fade_to_black",
    }
}

string_enum! {
    pub enum CharacterLoraScope {
        Project => "project",
        Global => "global",
        External => "external",
    }
}

string_enum! {
    pub enum RecipePresetScope {
        Builtin => "builtin",
        Global => "global",
        Project => "project",
    }
}

string_enum! {
    pub enum RecipePresetWorkflow {
        TextToImage => "text_to_image",
        ImageEdit => "edit_image",
        ImageToVideo => "image_to_video",
        TextToVideo => "text_to_video",
        FirstLastFrame => "first_last_frame",
    }
}

string_enum! {
    pub enum ModelKind {
        Image => "image",
        Video => "video",
        Utility => "utility",
    }
}

string_enum! {
    pub enum ModelCapability {
        TextToImage => "text_to_image",
        ImageEdit => "image_edit",
        CharacterImage => "character_image",
        StyleVariations => "style_variations",
        TextToVideo => "text_to_video",
        ImageToVideo => "image_to_video",
        VideoExtend => "video_extend",
        VideoBridge => "video_bridge",
        PersonReplace => "person_replace",
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JobProtocolFixture {
    pub schema_version: u32,
    pub job_types: Vec<JobType>,
    pub statuses: Vec<JobStatus>,
    pub active_statuses: Vec<JobStatus>,
    pub terminal_statuses: Vec<JobStatus>,
    pub non_gpu_job_types: Vec<JobType>,
    pub worker_statuses: Vec<WorkerStatus>,
    pub progress_stages: Vec<ProgressStage>,
    pub sse_events: Vec<SseEvent>,
    pub worker_capability_profiles: BTreeMap<String, Vec<WorkerCapability>>,
    pub requests: JobProtocolRequests,
    pub job_snapshot: JobSnapshot,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JobProtocolRequests {
    pub create_job: JobCreateRequest,
    pub register_worker: WorkerRegisterRequest,
    pub heartbeat: WorkerHeartbeatRequest,
    pub progress: ProgressRequest,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JobCreateRequest {
    #[serde(rename = "type")]
    pub job_type: JobType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_name: Option<String>,
    pub payload: JsonObject,
    pub requested_gpu: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ImageUpscaleRequest {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default = "default_image_upscale_factor")]
    pub factor: u8,
    #[serde(default = "default_image_upscale_engine")]
    pub engine: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

impl Default for ImageUpscaleRequest {
    fn default() -> Self {
        Self {
            enabled: false,
            factor: default_image_upscale_factor(),
            engine: default_image_upscale_engine(),
            extra: ExtraFields::default(),
        }
    }
}

impl ImageUpscaleRequest {
    pub fn is_disabled(&self) -> bool {
        !self.enabled
    }
}

pub const fn default_image_upscale_factor() -> u8 {
    2
}

pub fn default_image_upscale_engine() -> String {
    "real-esrgan".to_owned()
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkerRegisterRequest {
    pub worker_id: String,
    pub gpu_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gpu_name: Option<String>,
    pub capabilities: Vec<WorkerCapability>,
    pub loaded_models: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utilization: Option<WorkerUtilizationSnapshot>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkerHeartbeatRequest {
    pub status: WorkerStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_job_id: Option<String>,
    pub loaded_models: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utilization: Option<WorkerUtilizationSnapshot>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProgressRequest {
    pub status: JobStatus,
    pub stage: ProgressStage,
    pub progress: ContractNumber,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<JsonObject>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eta_seconds: Option<ContractNumber>,
    /// Sampled GPU memory usage percentage (0..100) at this progress point.
    /// The server tracks the running max across a job's progress reports so a
    /// completed row's meters can show the peak after the job finishes
    /// (sc-2086).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub peak_gpu_memory_pct: Option<ContractNumber>,
    /// Sampled GPU load percentage (0..100) at this progress point. Same
    /// running-max treatment as peak_gpu_memory_pct (sc-2086).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub peak_gpu_load_pct: Option<ContractNumber>,
    /// Runtime backend the worker actually executed this job on
    /// ("mlx" / "mps" / "cuda" / "cpu"). Distinct from the worker's
    /// device-architecture heuristic — the same Apple-Silicon worker can
    /// serve both MLX and MPS-Diffusers jobs, and the WorkerProgressCard's
    /// arch pill should reflect which one ran. First non-null value sticks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Id of the worker reporting this progress. When present, the server
    /// rejects the report with 409 unless the job's `worker_id` still matches —
    /// so a zombie worker whose job was swept to `interrupted` or reclaimed
    /// can't resurrect it (sc-4172). Omitted = legacy trusted caller.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JobSnapshot {
    pub id: String,
    #[serde(rename = "type")]
    pub job_type: JobType,
    pub status: JobStatus,
    pub project_id: Option<String>,
    pub project_name: Option<String>,
    pub payload: JsonObject,
    pub result: JsonObject,
    pub requested_gpu: String,
    pub assigned_gpu: Option<String>,
    pub worker_id: Option<String>,
    pub progress: ContractNumber,
    pub stage: ProgressStage,
    pub message: String,
    pub error: Option<String>,
    pub eta_seconds: Option<ContractNumber>,
    pub elapsed_seconds: Option<ContractNumber>,
    pub attempts: u32,
    pub source_job_id: Option<String>,
    pub duplicate_of_job_id: Option<String>,
    pub cancel_requested: bool,
    pub created_at: String,
    pub updated_at: String,
    pub started_at: Option<String>,
    pub completed_at: Option<String>,
    pub canceled_at: Option<String>,
    pub last_heartbeat_at: Option<String>,
    /// Highest GPU memory percentage the worker observed for this job (0..100).
    /// Populated by sc-2086 and read by the WorkerProgressCard hardware row on
    /// terminal jobs so static meters reflect the peak observed during the run.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub peak_gpu_memory_pct: Option<ContractNumber>,
    /// Highest GPU load percentage the worker observed for this job (0..100).
    /// Pair of peak_gpu_memory_pct.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub peak_gpu_load_pct: Option<ContractNumber>,
    /// Runtime backend the worker actually used to execute the job
    /// ("mlx" / "mps" / "cuda" / "cpu"). Surfaced by the WorkerProgressCard
    /// arch pill so an MLX run and a Diffusers-on-MPS run on the same worker
    /// read differently.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Human-readable job title derived server-side from job type + payload
    /// (sc-2087). The WorkerProgressCard reads `title` first and only falls
    /// back to client-side derivation when this is absent, so queue rows
    /// always show something more meaningful than the bare job id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResourceSidecarsFixture {
    pub schema_version: u32,
    pub project_folders: Vec<String>,
    pub sidecar_patterns: SidecarPatterns,
    pub fixtures: Vec<SidecarFixtureDescriptor>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QueueSummary {
    pub counts: BTreeMap<JobStatus, u32>,
    pub active_jobs: Vec<JobSnapshot>,
    pub workers: Vec<WorkerSnapshot>,
    pub max_job_attempts: u32,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkerSnapshot {
    pub id: String,
    pub gpu_id: String,
    pub gpu_name: Option<String>,
    pub status: WorkerStatus,
    pub current_job_id: Option<String>,
    pub capabilities: Vec<WorkerCapability>,
    pub loaded_models: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub utilization: Option<WorkerUtilizationSnapshot>,
    pub registered_at: String,
    pub last_seen_at: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkerUtilizationSnapshot {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory_total_mb: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory_used_mb: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub memory_free_mb: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gpu_load_percent: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClaimRequest {
    pub worker_id: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClaimResponse {
    pub job: Option<JobSnapshot>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DuplicateJobRequest {
    pub payload_changes: JsonObject,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requested_gpu: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RetryJobRequest {
    #[serde(default)]
    pub payload_changes: JsonObject,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SidecarPatterns {
    pub project: String,
    pub asset: String,
    pub character: String,
    pub timeline: String,
    pub person_track: String,
    pub generation_set: String,
    pub recipe: String,
    pub model_install_marker: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SidecarFixtureDescriptor {
    pub name: String,
    pub path: String,
    pub required_top_level_keys: Vec<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    pub schema_version: u32,
    pub app_version: String,
    pub id: String,
    pub name: String,
    pub created_at: String,
    pub folders: BTreeMap<String, String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Asset {
    pub schema_version: u32,
    pub id: String,
    pub project_id: String,
    pub generation_set_id: Option<String>,
    #[serde(rename = "type")]
    pub asset_type: AssetType,
    pub display_name: String,
    pub created_at: String,
    pub file: AssetFile,
    pub status: AssetStatus,
    pub recipe: Recipe,
    pub lineage: AssetLineage,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssetFile {
    pub path: String,
    pub mime_type: String,
    pub width: Option<u32>,
    pub height: Option<u32>,
    pub duration: Option<ContractNumber>,
    pub fps: Option<ContractNumber>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssetStatus {
    pub favorite: bool,
    pub rating: u8,
    pub rejected: bool,
    pub trashed: bool,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AssetLineage {
    pub parents: Vec<String>,
    pub source_asset_id: Option<String>,
    pub source_timestamp: Option<ContractNumber>,
    pub job_id: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

/// One ordered piece of an interleaved document: either a text run or a reference
/// to a generated `image` asset. The producer (worker, sc-1606) splits the model's
/// output text on its inline `<image>` markers and slots the images in order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DocumentSegment {
    #[serde(rename = "type")]
    pub segment_type: DocumentSegmentKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

/// On-disk schema for an interleaved text-image document, stored at
/// `assets/documents/<id>.json`. The companion `<id>.sceneworks.json` is a regular
/// `Asset` of type `document` whose `file.path` points here. See sc-1576 / sc-1605.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InterleavedDocument {
    pub schema_version: u32,
    pub id: String,
    pub project_id: String,
    pub job_id: Option<String>,
    pub model: String,
    pub prompt: String,
    pub created_at: String,
    pub segments: Vec<DocumentSegment>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerationSet {
    pub schema_version: u32,
    pub id: String,
    pub project_id: String,
    pub job_id: Option<String>,
    pub mode: ContractMode,
    pub model: String,
    pub prompt: String,
    pub negative_prompt: String,
    pub count: u32,
    pub created_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<Recipe>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Recipe {
    pub mode: ContractMode,
    pub model: String,
    pub adapter: RecipeAdapter,
    pub prompt: String,
    pub negative_prompt: String,
    pub seed: i64,
    pub loras: Vec<JsonObject>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub style_preset: Option<String>,
    pub normalized_settings: JsonObject,
    pub raw_adapter_settings: JsonObject,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Character {
    pub schema_version: u32,
    pub id: String,
    pub project_id: String,
    pub name: String,
    #[serde(rename = "type")]
    pub character_type: CharacterType,
    pub description: String,
    pub created_at: String,
    pub updated_at: String,
    pub status: CharacterStatus,
    pub references: Vec<CharacterReference>,
    pub looks: Vec<CharacterLook>,
    pub loras: Vec<CharacterLora>,
    pub trained_loras: Vec<JsonObject>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CharacterStatus {
    pub archived: bool,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CharacterReference {
    pub asset_id: String,
    pub approved: bool,
    pub role: CharacterReferenceRole,
    pub notes: String,
    pub added_at: String,
    pub approved_at: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CharacterLook {
    pub id: String,
    pub name: String,
    pub description: String,
    pub approved_reference_ids: Vec<String>,
    pub recipe_settings: JsonObject,
    pub created_at: String,
    pub updated_at: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CharacterLora {
    pub id: String,
    pub lora_id: Option<String>,
    pub name: String,
    pub source_path: Option<String>,
    pub project_path: Option<String>,
    pub copied_into_project: bool,
    pub category: CharacterLoraCategory,
    pub scope: CharacterLoraScope,
    pub trigger_words: Vec<String>,
    pub default_weight: ContractNumber,
    pub compatibility: JsonObject,
    pub created_at: String,
    pub updated_at: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Timeline {
    pub schema_version: u32,
    pub id: String,
    pub project_id: String,
    pub name: String,
    pub aspect_ratio: TimelineAspectRatio,
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    pub duration: ContractNumber,
    pub tracks: Vec<TimelineTrack>,
    pub transitions: Vec<TimelineTransition>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineTrack {
    pub id: String,
    pub name: String,
    pub kind: TimelineTrackKind,
    pub locked: bool,
    pub muted: bool,
    pub items: Vec<TimelineItem>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineItem {
    pub id: String,
    pub track_id: String,
    pub asset_id: String,
    #[serde(rename = "type")]
    pub item_type: TimelineItemType,
    pub display_name: String,
    pub source_in: ContractNumber,
    pub source_out: ContractNumber,
    pub timeline_start: ContractNumber,
    pub timeline_end: ContractNumber,
    pub speed: ContractNumber,
    pub fit: TimelineFitMode,
    pub volume: ContractNumber,
    pub version_asset_ids: Vec<String>,
    pub current_version_asset_id: Option<String>,
    pub version_history: Vec<TimelineVersion>,
    pub transition_in: Option<TimelineTransition>,
    pub transition_out: Option<TimelineTransition>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineVersion {
    pub asset_id: String,
    pub created_at: Option<String>,
    pub source: TimelineVersionSource,
    pub job_id: Option<String>,
    pub note: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineTransition {
    pub id: String,
    #[serde(rename = "type")]
    pub transition_type: TimelineTransitionType,
    pub from_item_id: Option<String>,
    pub to_item_id: Option<String>,
    pub duration: ContractNumber,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersonTrack {
    pub schema_version: u32,
    pub id: String,
    pub project_id: String,
    pub name: String,
    pub created_at: String,
    pub source_asset_id: String,
    pub source_display_name: Option<String>,
    pub representative_frame_asset_id: String,
    pub selected_detection: PersonDetection,
    pub frames: Vec<PersonTrackFrame>,
    pub corrections: Vec<Value>,
    pub status: PersonTrackStatus,
    pub recipe: Recipe,
    pub lineage: JsonObject,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersonDetection {
    pub id: String,
    #[serde(rename = "box")]
    pub box_: NormalizedBox,
    pub confidence: ContractNumber,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersonTrackFrame {
    pub timestamp: ContractNumber,
    #[serde(rename = "box")]
    pub box_: NormalizedBox,
    pub confidence: ContractNumber,
    #[serde(default, skip_serializing_if = "MaybePresent::is_missing")]
    pub mask: MaybePresent<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NormalizedBox {
    pub x: ContractNumber,
    pub y: ContractNumber,
    pub width: ContractNumber,
    pub height: ContractNumber,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersonTrackStatus {
    pub sample_rate_fps: ContractNumber,
    pub mask_state: PersonTrackMaskState,
    pub average_confidence: ContractNumber,
    pub correction_state: PersonTrackCorrectionState,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelManifest {
    pub schema_version: u32,
    pub models: Vec<ModelManifestEntry>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelManifestEntry {
    pub id: String,
    pub name: String,
    pub family: String,
    #[serde(rename = "type")]
    pub model_type: ModelKind,
    pub adapter: String,
    pub capabilities: Vec<ModelCapability>,
    pub downloads: Vec<ModelDownload>,
    pub paths: BTreeMap<String, String>,
    pub defaults: JsonObject,
    pub limits: JsonObject,
    pub lora_compatibility: JsonObject,
    pub ui: JsonObject,
    /// Machine-readable signal that the download is gated and needs a credential
    /// (e.g. an accepted license + token) before it can be fetched. The Models
    /// screen uses this to point the user at the credential screen (sc-1898).
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub gated: bool,
    /// Credential host the gated download requires (e.g. `huggingface.co`). When
    /// omitted the catalog derives it from the download provider/source URL.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credential_host: Option<String>,
    /// Optional license/model-card URL the user must accept (surfaced as a
    /// "Review license" link next to the gated notice).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub license_url: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelDownload {
    pub provider: String,
    pub repo: String,
    pub files: Vec<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoraManifest {
    pub schema_version: u32,
    pub loras: Vec<LoraManifestEntry>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoraManifestEntry {
    pub id: String,
    pub name: String,
    pub family: String,
    pub trigger_words: Vec<String>,
    pub compatibility: JsonObject,
    pub source: JsonObject,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecipePresetManifest {
    pub schema_version: u32,
    pub presets: Vec<RecipePresetManifestEntry>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecipePresetManifestEntry {
    pub id: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<RecipePresetScope>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order: Option<i64>,
    pub workflow: RecipePresetWorkflow,
    pub model: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub modes: Vec<ContractMode>,
    #[serde(default, skip_serializing_if = "RecipePresetDefaults::is_empty")]
    pub defaults: RecipePresetDefaults,
    #[serde(default, skip_serializing_if = "RecipePresetPrompt::is_empty")]
    pub prompt: RecipePresetPrompt,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub loras: Vec<RecipePresetLora>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecipePresetDefaults {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub negative_prompt: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

impl RecipePresetDefaults {
    pub fn is_empty(&self) -> bool {
        self.count.is_none()
            && self.resolution.is_none()
            && self.negative_prompt.is_none()
            && self.extra.is_empty()
    }
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecipePresetPrompt {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

impl RecipePresetPrompt {
    pub fn is_empty(&self) -> bool {
        self.prefix.is_none() && self.suffix.is_none() && self.extra.is_empty()
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecipePresetLora {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compatibility: Option<JsonObject>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub weight: Option<ContractNumber>,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelInstallMarker {
    pub repo: String,
    pub model_id: String,
    pub model_name: String,
    pub job_id: String,
    pub completed_at: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn image_upscale_request_round_trips_when_present() {
        let value = json!({
            "enabled": true,
            "factor": 4,
            "engine": "real-esrgan"
        });

        let request: ImageUpscaleRequest =
            serde_json::from_value(value.clone()).expect("upscale request parses");

        assert!(request.enabled);
        assert_eq!(request.factor, 4);
        assert_eq!(request.engine, "real-esrgan");
        assert_eq!(
            serde_json::to_value(request).expect("upscale request serializes"),
            value
        );
    }

    #[test]
    fn image_upscale_request_defaults_to_disabled() {
        let request: ImageUpscaleRequest =
            serde_json::from_value(json!({})).expect("empty upscale request parses");

        assert!(request.is_disabled());
        assert_eq!(request.factor, 2);
        assert_eq!(request.engine, "real-esrgan");
    }

    #[test]
    fn non_gated_model_entry_omits_gated_fields() {
        // The common case: a non-gated entry must not gain `gated`/`credentialHost`/
        // `licenseUrl` keys on serialize (keeps existing manifests/fixtures stable).
        let entry: ModelManifestEntry = serde_json::from_value(json!({
            "id": "z_image_turbo",
            "name": "Z-Image-Turbo",
            "family": "z-image",
            "type": "image",
            "adapter": "z_image_diffusers",
            "capabilities": ["text_to_image"],
            "downloads": [{ "provider": "huggingface", "repo": "Tongyi-MAI/Z-Image-Turbo", "files": [] }],
            "paths": {},
            "defaults": {},
            "limits": {},
            "loraCompatibility": {},
            "ui": {}
        }))
        .expect("entry parses");

        assert!(!entry.gated);
        assert_eq!(entry.credential_host, None);
        let encoded = serde_json::to_value(&entry).expect("entry serializes");
        let object = encoded.as_object().expect("object");
        assert!(!object.contains_key("gated"));
        assert!(!object.contains_key("credentialHost"));
        assert!(!object.contains_key("licenseUrl"));
    }

    #[test]
    fn gated_model_entry_round_trips() {
        let value = json!({
            "id": "flux_dev",
            "name": "FLUX.1 [dev]",
            "family": "flux",
            "type": "image",
            "adapter": "flux_diffusers",
            "capabilities": ["text_to_image"],
            "downloads": [{ "provider": "huggingface", "repo": "black-forest-labs/FLUX.1-dev", "files": [] }],
            "paths": {},
            "defaults": {},
            "limits": {},
            "loraCompatibility": {},
            "ui": {},
            "gated": true,
            "credentialHost": "huggingface.co",
            "licenseUrl": "https://huggingface.co/black-forest-labs/FLUX.1-dev"
        });
        let entry: ModelManifestEntry =
            serde_json::from_value(value.clone()).expect("gated entry parses");

        assert!(entry.gated);
        assert_eq!(entry.credential_host.as_deref(), Some("huggingface.co"));
        assert_eq!(
            entry.license_url.as_deref(),
            Some("https://huggingface.co/black-forest-labs/FLUX.1-dev")
        );
        assert_eq!(
            serde_json::to_value(entry).expect("gated entry serializes"),
            value
        );
    }

    #[test]
    fn chroma_diffusers_recipe_adapter_round_trips() {
        assert_eq!(RecipeAdapter::ChromaDiffusers.as_str(), "chroma_diffusers");
        let parsed: RecipeAdapter =
            serde_json::from_value(json!("chroma_diffusers")).expect("chroma adapter parses");
        assert_eq!(parsed, RecipeAdapter::ChromaDiffusers);
        assert_eq!(
            serde_json::to_value(RecipeAdapter::ChromaDiffusers)
                .expect("chroma adapter serializes"),
            json!("chroma_diffusers")
        );
    }

    #[test]
    fn sdxl_diffusers_recipe_adapter_round_trips() {
        assert_eq!(RecipeAdapter::SdxlDiffusers.as_str(), "sdxl_diffusers");
        let parsed: RecipeAdapter =
            serde_json::from_value(json!("sdxl_diffusers")).expect("sdxl adapter parses");
        assert_eq!(parsed, RecipeAdapter::SdxlDiffusers);
        assert_eq!(
            serde_json::to_value(RecipeAdapter::SdxlDiffusers).expect("sdxl adapter serializes"),
            json!("sdxl_diffusers")
        );
    }
}
